changelog:
  exclude:
    labels:
      - ignore
    authors:
      - octocat
  categories:
    - title: '🚀 Features'
      labels:
        - feature
        - enhancement
    - title: '🐛 Bug Fixes'
      labels:
        - bug
        - fix
    - title: '💅 Polish'
      labels:
        - UI
        - UX
        - design
    - title: '🛠️ Refactoring'
      labels:
        - refactor
    - title: '📦 Dependency Updates'
      labels:
        - dependencies
    - title: '📖 Documentation'
      labels:
        - documentation
    - title: '🚧 Implementation details'
      labels:
        - logic
    - title: '🧪 Testing'
      labels:
        - test
    - title: '🧹 Chore'
      labels:
        - chore