name: Linux Builds
on:
  workflow_dispatch:
    inputs:
      clean_cache:
        description: 'Clean NPM cache'
        required: false
        type: boolean
        default: false
jobs:
  build-linux:
    name: Build Linux ${{ matrix.target }}
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: 'AppImage'
            ext: 'AppImage'
          - target: 'deb'
            ext: 'deb'
          - target: 'rpm'
            ext: 'rpm'
          - target: 'snap'
            ext: 'snap'
          - target: 'tar.gz'
            ext: 'tar.gz'
    steps:
      - name: Checkout Source Code
        uses: actions/checkout@v4
        with:
          lfs: false
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '25'
          cache: 'npm'
      - name: Install System Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y rpm libarchive-tools fakeroot dpkg-dev libsecret-1-dev libfuse2 libgl1-mesa-dev build-essential graphicsmagick
          sudo snap install snapcraft --classic
      - name: Clean NPM Cache (Optional)
        if: ${{ inputs.clean_cache }}
        run: npm cache clean --force
      - name: Install NPM Dependencies
        run: npm ci --silent
      - name: Build Application
        shell: bash
        run: |
          node helpers/builder.js --linux --target=${{ matrix.target }} -c.publish=never
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Linux-${{ matrix.target }}
          path: |
            release/*.${{ matrix.ext }}
          if-no-files-found: warn
          retention-days: 5
